apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-ontap-nas-032
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"
  selector: "serial=032"
allowVolumeExpansion: true
volumeBindingMode: Immediate
