apiVersion: v1
kind: Service
metadata:
  name: vm1-ssh-service
  namespace: test
spec:
  selector:
    kubevirt.io/domain: ssh   # 위 VMI와 일치
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022    # 외부에서 접근할 NodePort (30000~32767 사이)
  type: NodePort
