apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: my-vm
  namespace: my-vm-namespace
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ssh
    spec:
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 1Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 30
