apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: AKIA39557566D4D80238
  access_key_secret: Z6x0q3cNqaOumwKZT3kEdWYuw6pq0bmH6r4eovJU
  bucketnames: redhat-poc
  endpoint: https://yiobj2.l-cloud.co.kr
