apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: nad-svc-2137
  namespace: 21-network
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "nad-svc-2137",
        "type": "ovn-k8s-cni-overlay",
        "physicalNetworkName": "localnet2",
        "netAttachDefName": "21-network/nad-svc-2137",
        "topology": "localnet",
        "vlanID": 2137
    }
