apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-virt
spec:
  desiredState:
    interfaces:
    - link-aggregation:
        mode: active-backup
        port:
        - enp7s0
        - enp8s0
      name: bond-virt
      state: up
      type: bond
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: bond-virt
      name: ovs-br-virt
      state: absent
      type: ovs-bridge
    ovn:
      bridge-mappings:
      - bridge: ovs-br-virt
        localnet: localnet2
        state: present
  nodeSelector:
    net: br-virt
